language: java
install: true

jdk:
  - oraclejdk8

sudo: false

script:
  - java -version
  - wget https://services.gradle.org/distributions/gradle-4.9-bin.zip
  - ls
  - mkdir ../.gradle
  - unzip gradle-4.9-bin.zip -d ../.gradle
  - ./gradlew --version

notifications:
  email: false