language: java
install: true

jdk:
  - oraclejdk8

sudo: false

script:
  - java -version
  - wget https://services.gradle.org/distributions/gradle-4.9-bin.zip
  - apt-get install unzip
  - ls

notifications:
  email: false